#KR population
#Load required library
```{r}
library(SeuratDisk)
library(Seurat)
library(scCustomize)
library(scater)
```

#1.Read DEGs results from Dream analyis 
```{r}
#KR outputs 
KR_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202603/Part4_AIDA_Age_Sex_DEGs_Output/KR_AIDA"
KR_AIDA_Myeloid_pDC_dream_modelFit_eBayes <- readRDS(file.path(KR_Output_PATH, "/KR_AIDA_Myeloid_pDC_dream_modelFit_eBayes.rds"))
KR_AIDA_NK_dream_modelFit_eBayes <- readRDS(file.path(KR_Output_PATH, "/KR_AIDA_NK_dream_modelFit_eBayes.rds"))
KR_AIDA_T_dream_modelFit_eBayes <- readRDS(file.path(KR_Output_PATH, "/KR_AIDA_T_dream_modelFit_eBayes.rds"))
KR_AIDA_B_dream_modelFit_eBayes <- readRDS(file.path(KR_Output_PATH, "/KR_AIDA_B_dream_modelFit_eBayes.rds"))
```

#Immune Cell types of interest
```{r}
Myeloid_pDC_Author_Annotation_celltype <- c("Myeloid_unknown", "CD14+_Monocyte", "CD16+_Monocyte", "cDC2")
NK_Author_Annotation_celltype <- c("NK_unknown", "CD16+_NK", "CD56+_NK")
T_Author_Annotation_celltype <- c("T_unknown", "CD4+_T_unknown", "CD4+_T_naive", "CD4+_T_cm",  "CD4+_T_cyt", "CD4+_T_em", "CD8+_T_unknown", "CD8+_T_naive", "CD8+_T_GZMBhi", "CD8+_T_GZMKhi", "MAIT",   "gdT_GZMBhi", "gdT_GZMKhi",  "Treg")
B_Author_Annotation_celltype <- c("B_unknown", "naive_B", "memory_B_IGHMlo", "memory_B_IGHMhi")
```

#Prepare input for CCC analysis
#2.DEGs impacted by Red ancestry in KR
```{r}
#Only upregulated genes by Red ancestry
#Myeloid_pDC
KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref <- list()
KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_diffexpressed <- list()
KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_UP <- list()
for (i in Myeloid_pDC_Author_Annotation_celltype) {
  KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref[[i]] <- topTable(KR_AIDA_Myeloid_pDC_dream_modelFit_eBayes[[i]], coef = "Red_ref", adjust="BH", number = Inf) 
  KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref[[i]]$Author_Annotation <- i
  KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_diffexpressed[[i]] <- data.frame(KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref[[i]]) %>%  
  mutate(diffexpressed = case_when(logFC > 1 & adj.P.Val < 0.05 ~ "Upregulated", 
                                   logFC < -1 & adj.P.Val < 0.05 ~ "Downregulated",
                                   TRUE ~ "Not significant"))
  KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_UP[[i]] <- subset(KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_diffexpressed[[i]], diffexpressed == "Upregulated")
  KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_UP[[i]]$gene <- rownames(KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_UP[[i]])
}

#NK
KR_AIDA_NK_dream_modelFit_Red_ref <- list()
KR_AIDA_NK_dream_modelFit_Red_ref_diffexpressed <- list()
KR_AIDA_NK_dream_modelFit_Red_ref_UP <- list()
for (i in NK_Author_Annotation_celltype) {
  KR_AIDA_NK_dream_modelFit_Red_ref[[i]] <- topTable(KR_AIDA_NK_dream_modelFit_eBayes[[i]], coef = "Red_ref", adjust="BH", number = Inf) 
  KR_AIDA_NK_dream_modelFit_Red_ref[[i]]$Author_Annotation <- i
  KR_AIDA_NK_dream_modelFit_Red_ref_diffexpressed[[i]] <- data.frame(KR_AIDA_NK_dream_modelFit_Red_ref[[i]]) %>%
    mutate(diffexpressed = case_when(logFC > 1 & adj.P.Val < 0.05 ~ "Upregulated", 
                                     logFC < -1 & adj.P.Val < 0.05 ~ "Downregulated",
                                TRUE ~ "Not significant"))
  KR_AIDA_NK_dream_modelFit_Red_ref_UP[[i]] <- subset(KR_AIDA_NK_dream_modelFit_Red_ref_diffexpressed[[i]], diffexpressed == "Upregulated")
  KR_AIDA_NK_dream_modelFit_Red_ref_UP[[i]]$gene <- rownames(KR_AIDA_NK_dream_modelFit_Red_ref_UP[[i]])
}

#T
KR_AIDA_T_dream_modelFit_Red_ref <- list()
KR_AIDA_T_dream_modelFit_Red_ref_diffexpressed <- list()
KR_AIDA_T_dream_modelFit_Red_ref_UP <- list()
for (i in T_Author_Annotation_celltype) {
  KR_AIDA_T_dream_modelFit_Red_ref[[i]] <- topTable(KR_AIDA_T_dream_modelFit_eBayes[[i]], coef = "Red_ref", adjust="BH", number = Inf) 
  KR_AIDA_T_dream_modelFit_Red_ref[[i]]$Author_Annotation <- i
  KR_AIDA_T_dream_modelFit_Red_ref_diffexpressed[[i]] <- data.frame(KR_AIDA_T_dream_modelFit_Red_ref[[i]]) %>%  
  mutate(diffexpressed = case_when(logFC > 1 & adj.P.Val < 0.05 ~ "Upregulated", 
                                   logFC < -1 & adj.P.Val < 0.05 ~ "Downregulated",
                                   TRUE ~ "Not significant"))
  KR_AIDA_T_dream_modelFit_Red_ref_UP[[i]] <- subset(KR_AIDA_T_dream_modelFit_Red_ref_diffexpressed[[i]], diffexpressed == "Upregulated")
  KR_AIDA_T_dream_modelFit_Red_ref_UP[[i]]$gene <- rownames(KR_AIDA_T_dream_modelFit_Red_ref_UP[[i]])
}

#B
KR_AIDA_B_dream_modelFit_Red_ref <- list()
KR_AIDA_B_dream_modelFit_Red_ref_diffexpressed <- list()
KR_AIDA_B_dream_modelFit_Red_ref_UP <- list()
for (i in B_Author_Annotation_celltype) {
  KR_AIDA_B_dream_modelFit_Red_ref[[i]] <- topTable(KR_AIDA_B_dream_modelFit_eBayes[[i]], coef = "Red_ref", adjust="BH", number = Inf) 
  KR_AIDA_B_dream_modelFit_Red_ref[[i]]$Author_Annotation <- i
  KR_AIDA_B_dream_modelFit_Red_ref_diffexpressed[[i]] <- data.frame(KR_AIDA_B_dream_modelFit_Red_ref[[i]]) %>%  
  mutate(diffexpressed = case_when(logFC > 1 &   adj.P.Val < 0.05 ~ "Upregulated", 
                                   logFC < -1 & adj.P.Val < 0.05 ~ "Downregulated",
                                   TRUE ~ "Not significant"))
  KR_AIDA_B_dream_modelFit_Red_ref_UP[[i]] <- subset(KR_AIDA_B_dream_modelFit_Red_ref_diffexpressed[[i]], diffexpressed == "Upregulated")
  KR_AIDA_B_dream_modelFit_Red_ref_UP[[i]]$gene <- rownames(KR_AIDA_B_dream_modelFit_Red_ref_UP[[i]])
}
```

```{r}
#Merge all cell types of upregulated DEGs by Red ancestry in the KR populations
KR_UPdge_Red_ref_All_celltypes_df <- rbind(KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_UP[["CD14+_Monocyte"]], KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_UP[["CD16+_Monocyte"]], KR_AIDA_Myeloid_pDC_dream_modelFit_Red_ref_UP[["cDC2"]],
KR_AIDA_NK_dream_modelFit_Red_ref_UP[["CD16+_NK"]],
KR_AIDA_T_dream_modelFit_Red_ref_UP[["T_unknown"]], KR_AIDA_T_dream_modelFit_Red_ref_UP[["CD4+_T_naive"]], KR_AIDA_T_dream_modelFit_Red_ref_UP[["CD4+_T_cm"]], KR_AIDA_T_dream_modelFit_Red_ref_UP[["CD4+_T_em"]], KR_AIDA_T_dream_modelFit_Red_ref_UP[["CD8+_T_unknown"]], KR_AIDA_T_dream_modelFit_Red_ref_UP[["CD8+_T_naive"]], KR_AIDA_T_dream_modelFit_Red_ref_UP[["CD8+_T_GZMBhi"]], KR_AIDA_T_dream_modelFit_Red_ref_UP[["CD8+_T_GZMKhi"]])

KR_UPdge_Red_ref_All_celltypes_df_select <- select(KR_UPdge_Red_ref_All_celltypes_df, Author_Annotation, gene, logFC, P.Value, adj.P.Val)
rownames(KR_UPdge_Red_ref_All_celltypes_df_select) <- NULL

#save DEG files
write_tsv(KR_UPdge_Red_ref_All_celltypes_df, file = "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/CCC/KR_UPdge_Red_ref_All_celltypes_df.tsv")
write_tsv(KR_UPdge_Red_ref_All_celltypes_df_select, file = "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/CCC/KR_UPdge_Red_ref_All_celltypes_df_select.tsv")
```

#3.Normalized count data per cell
```{r}
#KR outputs 
#Read files
#Myeloid + pDC
Myeloid_pDC_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202510/myeloid_pDC_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered <- readRDS(file.path(Myeloid_pDC_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered.rds"))
#NK
NK_ILC_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202511/NK_ILC_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered <- readRDS(file.path(NK_ILC_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered.rds"))
#T
T_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202511/T_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered <- readRDS(file.path(T_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered.rds"))
#B and Plasma Cells
B_PlasmaCell_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202511/B_PlasmaCell_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered <- readRDS(file.path(B_PlasmaCell_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered.rds"))

#Using normalized count matrix 
AIDA_normGEX_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/CCC"

#Myeloid_pDC cells in KR 
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_KR <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered, subset = Country == "KR")
#NK cells in KR 
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_KR <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered, subset = Country == "KR")
#T cells in KR 
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_KR <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered, subset = Country == "KR")
#B cells in KR 
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_QC_RPCA_joined_clustered_KR <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered, subset = Country == "KR")

#Merge all Seurat objects
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged <- merge(x = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_KR, y = list(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_KR, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_KR, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_QC_RPCA_joined_clustered_KR))
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined <- JoinLayers(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged)

DefaultAssay(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined)
Layers(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined[["RNA"]])

#Prepare data
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721 <- UpdateSeuratObject(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined)
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721 <- Add_Cell_QC_Metrics(object = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721, species = "human")

#single cell experiment
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_sce <- as.SingleCellExperiment(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721, assay = "RNA")
saveRDS(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_sce, "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202606/CCC/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_sce.rds")

Sys.setenv(RETICULATE_PYTHON = "/home/benjamaporn/miniconda3/bin/python3")
library(reticulate)
library(anndata)
as.anndata(x = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721, file_path = AIDA_normGEX_Output_PATH, file_name = "AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_anndata.h5ad")
```

#4.Create metadata
```{r}
library(tidyverse)
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_meta <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721@meta.data

#for CCC analysis
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_meta_select <- select(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_meta, barcode_name, Author_Annotation)
rownames(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_meta_select) <- NULL

#save
write_tsv(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_meta_select, file = "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/CCC/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_Allcelltypes_KR_merged_joined_20260721_meta_select.tsv")
```

