---
title: "Part4.1_AIDA_SLE_20260719"
author: "BZ"
date: "2026-07-19"
output: html_document
---

```{r}
library(AUCell)
library(Seurat)
library(SingleCellExperiment) 
library(ggplot2)
library(dplyr)
library(SCpubr)
```

#Read files
```{r}
#Seurat objects
#Myeloid + pDC
Myeloid_pDC_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202510/myeloid_pDC_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered <- readRDS(file.path(Myeloid_pDC_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered.rds"))
#NK
NK_ILC_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202511/NK_ILC_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered <- readRDS(file.path(NK_ILC_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered.rds"))
#T
T_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202511/T_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered <- readRDS(file.path(T_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered.rds"))
#B and Plasma Cells
B_PlasmaCell_Output_PATH <- "/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2025/Analysis202511/B_PlasmaCell_integration"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered <- readRDS(file.path(B_PlasmaCell_Output_PATH, "/AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered.rds"))

#AUC score
AIDA_myeloid_SLE_AUC_rankings <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_myeloid_SLE_AUC_rankings.rds")
AIDA_NK_ILC_SLE_AUC_rankings <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_NK_ILC_SLE_AUC_rankings.rds")
AIDA_T_SLE_AUC_rankings <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_T_SLE_AUC_rankings.rds")
AIDA_B_Plasma_Cell_SLE_AUC_rankings <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_B_Plasma_Cell_SLE_AUC_rankings.rds")

#Cell assignment
AIDA_myeloid_SLE_AUC_rankings_cells_assignment <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_myeloid_SLE_AUC_rankings_cells_assignment.rds")
AIDA_NK_ILC_SLE_AUC_rankings_cells_assignment <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_NK_ILC_SLE_AUC_rankings_cells_assignment.rds")
AIDA_T_SLE_AUC_rankings_cells_assignment <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_T_SLE_AUC_rankings_cells_assignment.rds")
AIDA_B_Plasma_Cell_SLE_AUC_rankings_cells_assignment <- readRDS("/mnt/icbs_shared_storage_general_2022/Benjamaporn/Analysis2026/Analysis202607/SLE/AUCell/AIDA_B_Plasma_Cell_SLE_AUC_rankings_cells_assignment.rds")
```

#1.Plot UMAP
```{r}
#NK
NK_ILC_Author_Annotation_col_dict <- c("NK_unknown"="#FFFFCC", "CD16+_NK"="#FFC44C",  "CD56+_NK"="#FF8000", "ILC"="#2CA02C")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_TH <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered, subset = Country == "TH")
Idents(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_TH) <- "Author_Annotation"
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_TH$Author_Annotation <- factor(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_TH$Author_Annotation, levels = c("NK_unknown", "CD16+_NK",  "CD56+_NK", "ILC"))
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_TH_Author_Annotation_umap <- DimPlot(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_TH, reduction = "umap", group.by = "Author_Annotation", label = TRUE, repel = TRUE, raster=FALSE, label.size = 2.5, cols = NK_ILC_Author_Annotation_col_dict) + labs(title = "NK and ILC in the Thai populations")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_TH_Author_Annotation_umap

#T
T_Author_Annotation_col_dict <- c("gdT_GZMKhi"="#827717", "gdT_GZMBhi"="#AFB42B", "dnT"="#CCE283", "CD8+_T_naive"="#AED581", "CD8+_T_unknown"="#8BC34A","CD8+_T_GZMBhi"="#689F38", "CD8+_T_GZMKhi"="#33691E",  "MAIT"="#C1C4C3", "T_unknown"="#E0F2F1", "CD4+_T_unknown"="#E8F5E9", "CD4+_T_naive"="#2E7D32", "CD4+_T_cm"="#66BB6A", "CD4+_T_em"="#A5D6A7",  "CD4+_T_cyt"="#43A047", "Treg"="#00796B")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_TH <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered, subset = Country == "TH")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_TH$Author_Annotation <- factor(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_TH$Author_Annotation, levels = c("gdT_GZMKhi", "gdT_GZMBhi", "dnT", "CD8+_T_naive", "CD8+_T_unknown","CD8+_T_GZMBhi", "CD8+_T_GZMKhi",  "MAIT", "T_unknown", "CD4+_T_unknown", "CD4+_T_naive", "CD4+_T_cm", "CD4+_T_em",  "CD4+_T_cyt", "Treg"))
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_TH_Author_Annotation_umap <- DimPlot(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_TH, reduction = "umap", group.by = "Author_Annotation", label = TRUE, repel = TRUE, raster=FALSE, label.size = 2.5, cols = T_Author_Annotation_col_dict) + labs(title = "T cells in the Thai populations")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_TH_Author_Annotation_umap

#B
B_PlasmaCell_Author_Annotation_col_dict <- c("B_unknown"="#B71C1C", "naive_B"="#D32F2F", "atypical_B"="#F44336", "memory_B_unknown"="#EC407A", "memory_B_IGHMhi"="#F48FB1", "memory_B_IGHMlo"="#FCE4EC", "Plasma_Cell"="#880E4F")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_TH <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered, subset = Country == "TH")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_TH$Author_Annotation <- factor(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_TH$Author_Annotation, levels = c("B_unknown", "naive_B", "atypical_B", "memory_B_unknown", "memory_B_IGHMhi", "memory_B_IGHMlo", "Plasma_Cell"))
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_TH_Author_Annotation_umap <- DimPlot(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_TH, reduction = "umap", group.by = "Author_Annotation", label = TRUE, repel = TRUE, raster=FALSE, label.size = 2.5, cols = B_PlasmaCell_Author_Annotation_col_dict) + labs(title = "B cells in the Thai populations")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_TH_Author_Annotation_umap
```
#2. AUC score per cell
```{r}
#Myeloid
AIDA_myeloid_SLE_AUC_rankings_matrix <- getAUC(AIDA_myeloid_SLE_AUC_rankings)
AIDA_myeloid_SLE_AUC_rankings_matrix_t <- t(AIDA_myeloid_SLE_AUC_rankings_matrix)
#NK
AIDA_NK_ILC_SLE_AUC_rankings_matrix <- getAUC(AIDA_NK_ILC_SLE_AUC_rankings)
AIDA_NK_ILC_SLE_AUC_rankings_matrix_t <- t(AIDA_NK_ILC_SLE_AUC_rankings_matrix)
#T
AIDA_T_SLE_AUC_rankings_matrix <- getAUC(AIDA_T_SLE_AUC_rankings)
AIDA_T_SLE_AUC_rankings_matrix_t <- t(AIDA_T_SLE_AUC_rankings_matrix)
#B_Plasma_Cell
AIDA_B_Plasma_Cell_SLE_AUC_rankings_matrix <- getAUC(AIDA_B_Plasma_Cell_SLE_AUC_rankings)
AIDA_B_Plasma_Cell_SLE_AUC_rankings_matrix_t <- t(AIDA_B_Plasma_Cell_SLE_AUC_rankings_matrix)

#Adding AUC score
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered$SLE_AUC_score <- AIDA_myeloid_SLE_AUC_rankings_matrix_t[colnames(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered), "geneSet1"]
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered$Sex_Chr <- ifelse(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered$Sex == "Female", "XX","XY")

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered$SLE_AUC_score <- AIDA_NK_ILC_SLE_AUC_rankings_matrix_t[colnames(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered), "geneSet1"]
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered$Sex_Chr <- ifelse(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered$Sex == "Female", "XX","XY")

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered$SLE_AUC_score <- AIDA_T_SLE_AUC_rankings_matrix_t[colnames(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered), "geneSet1"]
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered$Sex_Chr <- ifelse(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered$Sex == "Female", "XX","XY")

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered$SLE_AUC_score <- AIDA_B_Plasma_Cell_SLE_AUC_rankings_matrix_t[colnames(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered), "geneSet1"]
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered$Sex_Chr <- ifelse(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered$Sex == "Female", "XX","XY")
```

#3. Plot umap based on SLE AUC score
```{r fig.height=5, fig.width=9}
#ploting compare between sex
#only TH
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_scPlot_TH <- SCpubr::do_FeaturePlot(sample = subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered, subset = Country == "TH"), features = "SLE_AUC_score", split.by = "Sex_Chr", sequential.palette = "OrRd", pt.size = 0.8, plot.title = "Myeloid innate cells across Thai populations", min.cutoff = 0.02, max.cutoff = 0.41)
SCpubr::do_FeaturePlot(sample = subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered, subset = Country == "TH"), features = "SLE_AUC_score", split.by = "Sex_Chr", sequential.palette = "OrRd", pt.size = 0.8, plot.title = "", min.cutoff = 0.02, max.cutoff = 0.41)
SCpubr::do_FeaturePlot(sample = subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered, subset = Country == "TH"), features = "SLE_AUC_score", split.by = "Sex_Chr", sequential.palette = "OrRd", pt.size = 0.8, plot.title = "", min.cutoff = 0.02, max.cutoff = 0.41)
SCpubr::do_FeaturePlot(sample = subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered, subset = Country == "TH"), features = "SLE_AUC_score", split.by = "Sex_Chr", sequential.palette = "OrRd", pt.size = 0.8, plot.title = "", min.cutoff = 0.02, max.cutoff = 0.41)
```

```{r}
#Combine all cells from all cell types
library(dplyr)
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered@meta.data
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_meta <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered@meta.data
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_meta <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered@meta.data
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_meta <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered@meta.data
```

#4. All PBMCs (except platelets)
```{r fig.height=6, fig.width=6}
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta <- rbind(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_NK_ILC_QC_RPCA_joined_clustered_meta, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_T_QC_RPCA_joined_clustered_meta, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_B_Plasma_Cell_QC_RPCA_joined_clustered_meta)

#Metadata
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta %>% 
mutate(Country_eth = case_when(
                                 Ethnicity == "Korean" ~ "Korean",
                                 Ethnicity == "Japanese" ~ "Japanese",
                                 Ethnicity == "Malay" ~ "SG_Malay",
                                 Ethnicity == "Chinese" ~ "SG_Chinese",
                                 Ethnicity == "Indian" ~ "SG_Indian",
                                 Ethnicity == "Thai" ~ "Thai"
                              )) %>%
select(DCP_ID, Age, Sex_Chr, Blue_ref, Red_ref, Orange_ref, SLE_AUC_score, Country_eth, Country, Ethnicity, Author_Annotation)
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC$Country_eth <- factor(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC$Country_eth, levels = c("SG_Indian", "SG_Malay", "Thai", "SG_Chinese", "Korean", "Japanese"))

library(ggpubr)
Gender_col_dict <- c("XY" = "#298ccc", "XX" ="#c90076")

#Calculate average AUC score per individual
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_perindividual <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC %>% group_by(DCP_ID) %>% summarise(mean = mean(SLE_AUC_score))

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_perindividual_mean <- 
merge(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_perindividual, by = "DCP_ID") %>%
distinct(DCP_ID, .keep_all = TRUE) 
```

```{r fig.height=18, fig.width=20}
#Checked between cell types
Author_Annotation_col_dict <- c("CD34_HSPC"="#8C564B",  "Myeloid_unknown"="#01579B", "CD14+_Monocyte"="#CC5500", "CD16+_Monocyte"="#FFCA99",  "DC_SIGLEC6hi"="#006666", "cDC1"="#00FFFF", "cDC2"="#99FFFF", "pDC"="#30BCAD", "Platelet"="#9467BD", "NK_unknown"="#FFFFCC", "CD16+_NK"="#FFC44C",  "CD56+_NK"="#FF8000",  "gdT_GZMKhi"="#827717", "gdT_GZMBhi"="#AFB42B", "dnT"="#CCE283", "CD8+_T_naive"="#AED581", "CD8+_T_unknown"="#8BC34A","CD8+_T_GZMBhi"="#689F38", "CD8+_T_GZMKhi"="#33691E",  "MAIT"="#C1C4C3", "T_unknown"="#E0F2F1", "CD4+_T_unknown"="#E8F5E9", "CD4+_T_naive"="#2E7D32", "CD4+_T_cm"="#66BB6A", "CD4+_T_em"="#A5D6A7",  "CD4+_T_cyt"="#43A047", "Treg"="#00796B", "B_unknown"="#B71C1C", "naive_B"="#D32F2F", "atypical_B"="#F44336", "memory_B_unknown"="#EC407A", "memory_B_IGHMhi"="#F48FB1", "memory_B_IGHMlo"="#FCE4EC", "Plasma_Cell"="#880E4F", "ILC"="#2CA02C")

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC$Author_Annotation <- factor(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC$Author_Annotation, levels = c("Myeloid_unknown", "CD14+_Monocyte", "CD16+_Monocyte",  "DC_SIGLEC6hi", "cDC1", "cDC2", "pDC", "NK_unknown", "CD16+_NK",  "CD56+_NK", "ILC", "gdT_GZMKhi", "gdT_GZMBhi", "dnT", "CD8+_T_naive", "CD8+_T_unknown","CD8+_T_GZMBhi", "CD8+_T_GZMKhi",  "MAIT", "T_unknown", "CD4+_T_unknown", "CD4+_T_naive", "CD4+_T_cm", "CD4+_T_em",  "CD4+_T_cyt", "Treg", "B_unknown", "naive_B", "atypical_B", "memory_B_unknown", "memory_B_IGHMhi", "memory_B_IGHMlo", "Plasma_Cell"))
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_celltypes_plot <- ggboxplot(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC, x="Author_Annotation", y="SLE_AUC_score", outlier.shape=NA, size=0.5, facet.by = "Country_eth") +
facet_wrap(~Country_eth, nrow =2) +
geom_jitter(width = 0.08, size= 0.8, height=0, aes(color=Author_Annotation))  +
ylab("SLE AUC score per cell") +
xlab("")+
scale_color_manual(values=Author_Annotation_col_dict)+
theme(text = element_text(size = 24), axis.text.x = element_blank(), legend.position="bottom", strip.background = element_rect(colour="black", fill="white", size=1.5, linetype="solid")) + 
guides(color = guide_legend(override.aes = list(size = 8))) + 
labs(title = "", color = "") 
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_celltypes_plot
```
#5. All Myeloid innate cells
```{r fig.height=5, fig.width=15}
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta_SLE_AUC_perindividual <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta %>% group_by(DCP_ID) %>% summarise(mean = mean(SLE_AUC_score))

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta_SLE_AUC_perindividual_mean <- 
merge(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta_SLE_AUC_perindividual, by = "DCP_ID") %>%
distinct(DCP_ID, .keep_all = TRUE) 
```

#6. CD16+monocyte
```{r fig.height=5, fig.width=15}
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono <- subset(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta, Author_Annotation == "CD16+_Monocyte")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual <- AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono %>% group_by(DCP_ID) %>% summarise(mean = mean(SLE_AUC_score))

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean <- 
merge(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC, AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual, by = "DCP_ID") %>%
distinct(DCP_ID, .keep_all = TRUE) 
```

#7. Regression analysis
```{r }
#All AIDA
summary(lm(mean ~ Age + Sex_Chr + Blue_ref:Sex_Chr, data = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_perindividual_mean))
summary(lm(mean ~ Age + Sex_Chr + Blue_ref:Sex_Chr, data = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta_SLE_AUC_perindividual_mean))
summary(lm(mean ~ Age + Sex_Chr + Blue_ref:Sex_Chr, data = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean))

#TH and SG
AIDA_Blue_country <- c("TH", "SG")
SLE_AUC_AllCell_DCP_Blue_country <- list()
SLE_AUC_AllCell_DCP_Blue_lm_interaction <- list()
for (i in AIDA_Blue_country){
SLE_AUC_AllCell_DCP_Blue_country[[i]] <-  filter(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_perindividual_mean, Country == i)
SLE_AUC_AllCell_DCP_Blue_lm_interaction[[i]] <- summary(lm(mean ~ Age + Sex_Chr + Blue_ref:Sex_Chr, data = SLE_AUC_AllCell_DCP_Blue_country[[i]]))
}

SLE_AUC_Myeloid_pDC_DCP_Blue_country <- list()
SLE_AUC_Myeloid_pDC_DCP_Blue_lm_interaction <- list()
for (i in AIDA_Blue_country){
SLE_AUC_Myeloid_pDC_DCP_Blue_country[[i]] <-  filter(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta_SLE_AUC_perindividual_mean, Country == i)
SLE_AUC_Myeloid_pDC_DCP_Blue_lm_interaction[[i]] <- summary(lm(mean ~ Age + Sex_Chr + Blue_ref:Sex_Chr, data = SLE_AUC_Myeloid_pDC_DCP_Blue_country[[i]]))
}

SLE_AUC_CD16mono_DCP_Blue_country <- list()
SLE_AUC_CD16mono_DCP_Blue_lm_interaction <- list()
for (i in AIDA_Blue_country){
SLE_AUC_CD16mono_DCP_Blue_country[[i]] <-  filter(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean, Country == i)
SLE_AUC_CD16mono_DCP_Blue_lm_interaction[[i]] <- summary(lm(mean ~ Age + Sex_Chr + Blue_ref:Sex_Chr, data = SLE_AUC_CD16mono_DCP_Blue_country[[i]]))
}
```

#8. Visualization
```{r fig.height=4, fig.width=4}
#All PBMCs
All_AIDA_SLE_AUC_Allcell_perindividual_mean_Blue_lm <- 
ggplot(data = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_perindividual_mean, 
  aes(x = Blue_ref, y = mean, color = Sex_Chr)) +
  geom_point(size = 3, alpha = 0.7, shape = 19) +
  geom_smooth(method = "lm", se = F, formula = y ~ x) +
  labs(title = "All AIDA",
       x = "Blue ancestry",
       y = "Average SLE AUC score") +
  theme_classic() +
  scale_color_manual(name = "Sex", values = Gender_col_dict) +
  annotate(geom="text", x=0.6, y=0.20, label="XX:Blue ancestry, adj. P-value = 0.0157\nXY:Blue ancestry, adj. P-value = 0.5122", color="black", size=2)
All_AIDA_SLE_AUC_Allcell_perindividual_mean_Blue_lm 

#TH AIDA
All_AIDA_SLE_AUC_Allcell_perindividual_mean_Blue_lm_TH <- 
ggplot(data = SLE_AUC_AllCell_DCP_Blue_country[["TH"]], 
  aes(x = Blue_ref, y = mean, color = Sex_Chr)) +
  geom_point(size = 3, alpha = 0.7, shape = 19) +
  geom_smooth(method = "lm", se = F, formula = y ~ x) +
  labs(title = "Thai populations",
       x = "Blue ancestry",
       y = "Average SLE AUC score") +
  theme_classic() +
  scale_color_manual(name = "Sex", values = Gender_col_dict) +
  annotate(geom="text", x=0.6, y=0.20, label="XX:Blue ancestry, adj. P-value = 0.229\nXY:Blue ancestry, adj. P-value = 0.753", color="black", size=2)
All_AIDA_SLE_AUC_Allcell_perindividual_mean_Blue_lm_TH 
```

```{r fig.height=4, fig.width=4}
#Myeloid innate cells
All_AIDA_SLE_AUC_Myeloid_pDC_perindividual_mean_Blue_lm <- 
ggplot(data = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_meta_SLE_AUC_perindividual_mean, 
  aes(x = Blue_ref, y = mean, color = Sex_Chr)) +
  geom_point(size = 3, alpha = 0.7, shape = 19) +
  geom_smooth(method = "lm", se = F, formula = y ~ x) +
  labs(title = "All AIDA",
       x = "Blue ancestry",
       y = "Average SLE AUC score") +
  theme_classic() +
  scale_color_manual(name = "Sex", values = Gender_col_dict) +
  annotate(geom="text", x=0.5, y=0.3, label="XX:Blue ancestry, adjusted P-value = 0.0032\nXY:Blue ancestry, adjusted P-value = 0.2590", color="black", size=2.5)
All_AIDA_SLE_AUC_Myeloid_pDC_perindividual_mean_Blue_lm 

All_AIDA_SLE_AUC_Myeloid_pDC_perindividual_mean_Blue_lm_TH <- 
ggplot(data = SLE_AUC_Myeloid_pDC_DCP_Blue_country[["TH"]], 
  aes(x = Blue_ref, y = mean, color = Sex_Chr)) +
  geom_point(size = 3, alpha = 0.7, shape = 19) +
  geom_smooth(method = "lm", se = F, formula = y ~ x) +
  labs(title = "Thai populations",
       x = "Blue ancestry",
       y = "Average SLE AUC score") +
  theme_classic() +
  scale_color_manual(name = "Sex", values = Gender_col_dict) +
  annotate(geom="text", x=0.5, y=0.3, label="XX:Blue ancestry, adjusted P-value = 0.395\nXY:Blue ancestry, adjusted P-value = 0.428", color="black", size=2.5)
All_AIDA_SLE_AUC_Myeloid_pDC_perindividual_mean_Blue_lm_TH 
```

```{r fig.height=4, fig.width=4}
#CD16+ monocytes
All_AIDA_SLE_AUC_CD16mono_perindividual_mean_Blue_lm <- 
ggplot(data = AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean, 
  aes(x = Blue_ref, y = mean, color = Sex_Chr)) +
  geom_point(size = 3, alpha = 0.7, shape = 19) +
  geom_smooth(method = "lm", se = F, formula = y ~ x) +
  labs(title = "All AIDA",
       x = "Blue ancestry",
       y = "Average SLE AUC score") +
  theme_classic() +
  scale_color_manual(name = "Sex", values = Gender_col_dict) +
  annotate(geom="text", x=0.5, y=0.3, label="XX:Blue ancestry, adj. P-value = 0.00145\nXY:Blue ancestry, adj. P-value = 0.20926 ", color="black", size=2.5)
All_AIDA_SLE_AUC_CD16mono_perindividual_mean_Blue_lm 

All_AIDA_SLE_AUC_CD16mono_perindividual_mean_Blue_lm_TH <- 
ggplot(data = SLE_AUC_CD16mono_DCP_Blue_country[["TH"]], 
  aes(x = Blue_ref, y = mean, color = Sex_Chr)) +
  geom_point(size = 3, alpha = 0.7, shape = 19) +
  geom_smooth(method = "lm", se = F, formula = y ~ x) +
  labs(title = "Thai populations",
       x = "Blue ancestry",
       y = "Average SLE AUC score") +
  theme_classic() +
  scale_color_manual(name = "Sex", values = Gender_col_dict) +
  annotate(geom="text", x=0.5, y=0.3, label="XX:Blue ancestry, adj.P-value = 0.869\nXY:Blue ancestry, adj. P-value = 0.482", color="black", size=2.5)
All_AIDA_SLE_AUC_CD16mono_perindividual_mean_Blue_lm_TH 
```

#9. Regression results between XX and XY per ethnicity
```{r fig.height=5, fig.width=15}
AIDA_Blue_ethnicity <- c("Thai", "Malay", "Chinese")
SLE_AUC_CD16mono_DCP_Blue_eth <- list()
SLE_AUC_CD16mono_DCP_Blue_lm <- list()
for (i in AIDA_Blue_ethnicity){
SLE_AUC_CD16mono_DCP_Blue_eth[[i]] <-  filter(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_SLE_AUC_perindividual_mean, Ethnicity == i)
SLE_AUC_CD16mono_DCP_Blue_lm[[i]] <- summary(lm(mean ~ Blue_ref + Age + Sex_Chr, data = SLE_AUC_CD16mono_DCP_Blue_eth[[i]]))
}

AIDA_Red_ethnicity <- c("Korean", "Japanese")
SLE_AUC_CD16mono_DCP_Red_eth <- list()
SLE_AUC_CD16mono_DCP_Red_lm <- list()
for (i in AIDA_Red_ethnicity){
SLE_AUC_CD16mono_DCP_Red_eth[[i]] <-  filter(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean, Ethnicity == i)
SLE_AUC_CD16mono_DCP_Red_lm[[i]] <- summary(lm(mean ~ Red_ref + Age + Sex_Chr, data = SLE_AUC_CD16mono_DCP_Red_eth[[i]]))
}

#Orange
SLE_AUC_CD16mono_DCP_Orange_eth <-  filter(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean, Ethnicity == "Indian")
SLE_AUC_CD16mono_DCP_Orange_lm <- summary(lm(mean ~ Orange_ref + Age + Sex_Chr, data = SLE_AUC_CD16mono_DCP_Orange_eth))

#Add p-value manual
SLE_AUC_CD16mono_DCP_stat_sex_lm <- data.frame(
    Country_eth= c("SG_Indian", "SG_Malay", "Thai", "SG_Chinese", "Korean", "Japanese"),
    group1 = c("XX", "XX", "XX", "XX", "XX", "XX"),
    group2 = c("XY", "XY", "XY", "XY", "XY", "XY"),
    p.adj = c("*", "ns", "**", "*", "ns", "ns")
)
SLE_AUC_CD16mono_DCP_stat_sex_lm$Country_eth <- factor(SLE_AUC_CD16mono_DCP_stat_sex_lm$Country_eth, levels = c("SG_Indian", "SG_Malay", "Thai", "SG_Chinese", "Korean", "Japanese"))

AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean_SexLM_plot <- ggboxplot(AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean, x="Sex_Chr", y="mean", outlier.shape=NA, size=0.5, facet.by = "Country_eth") +
facet_grid(.~Country_eth) +
geom_jitter(width = 0.08, size= 0.8, height=0, aes(color=Sex_Chr))  +
ylab("Average SLE AUC score") +
xlab("")+
scale_color_manual(values=Gender_col_dict)+
theme(text = element_text(size = 16), axis.text.x = element_blank(), legend.position="bottom", strip.background = element_rect(colour="black", fill="white", size=1.5, linetype="solid")) + 
guides(color = guide_legend(override.aes = list(size = 8))) + 
stat_pvalue_manual(SLE_AUC_CD16mono_DCP_stat_sex_lm, label = "p.adj", hide.ns = T, y.position = 0.35, size = 4) + 
labs(title = "CD16+ monocytes (per individual)", col = "Sex")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean_SexLM_plot
```

#10. Save images
```{r}
#Fig.5F
pdf("/home/benjamaporn/AIDA/AIDA_Picture_manuscript/Part5_AIDA_MS/Fig.5F.pdf", width = 7, height = 4)
par(family = "Helvetica")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_Myeloid_pDC_merged_RPCA_joined_clustered_scPlot_TH
dev.off()

#Fig.5G
pdf("/home/benjamaporn/AIDA/AIDA_Picture_manuscript/Part5_AIDA_MS/Fig.5G.pdf", width = 15, height = 5)
par(family = "Helvetica")
AIDA_Phase1_DataFreeze_v2_Step03_Seurat_JPKRSGTH_All_celltypes_meta_CD16mono_perindividual_mean_SexLM_plot
dev.off()

#Fig.5H
pdf("/home/benjamaporn/AIDA/AIDA_Picture_manuscript/Part5_AIDA_MS/Fig.5H_All.pdf", width = 4, height = 4)
par(family = "Helvetica")
All_AIDA_SLE_AUC_Myeloid_pDC_perindividual_mean_Blue_lm
dev.off()

pdf("/home/benjamaporn/AIDA/AIDA_Picture_manuscript/Part5_AIDA_MS/Fig.5H_TH.pdf", width = 4, height = 4)
par(family = "Helvetica")
All_AIDA_SLE_AUC_Myeloid_pDC_perindividual_mean_Blue_lm_TH 
dev.off()
```


